# Generated by Django 2.0.6 on 2019-03-28 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmorder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='fstorenum',
        ),
    ]
