# Generated by Django 2.0.6 on 2019-03-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmorder', '0002_remove_foods_fstorenum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='is_selectded',
            new_name='is_selected',
        ),
    ]
